apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcdemoservice
spec:
  selector:
    matchLabels:
      app: grpcdemoservice
  template:
    metadata:
      labels:
        app: grpcdemoservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: naingoted/grpc-healthcheck-demo:1.0
          ports:
            - name: grpcdemo
              containerPort: 4500
          env:
            - name: PORT
              value: '4500'
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: DISABLE_DEBUGGER
          #   value: "1"
          readinessProbe:
            exec:
              command: ['/bin/grpcdemo_health_probe', '-addr=:4500']
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ['/bin/grpcdemo_health_probe', '-addr=:4500']
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: grpcdemoservice
spec:
  type: ClusterIP
  selector:
    app: grpcdemoservice
  ports:
    - name: grpcdemo
      port: 4500
      targetPort: 4500
